version: '3.1'

services:

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: order_management
    ports:
      - "5432:5432"
